### ISSUE TITLE
Turn off Load Error alert box

### ISSUE THREAD

**Issue by VinceG3** [fkchang/opal-hot-reloader#9]
Is there any way to turn off the alert boxes that get thrown up when it has a load error? I guess if it annoys me enough I'll figure out a way, and add a command line option.

**Comment by fkchang** [comment]
I can figure something out.  It's easy to make it a run time option.  I added the alerts because I getting load errors, but didn't know it, and it really messed me up because I kept expecting the changes to take effect - I didn't know the code being reloaded was bad. I suppose I can always log it, and make the alert optional (because I'm not always looking at the console, but I want to know when I'm hotloading bad code)

**Comment by fkchang** [comment]
So try master or 0.1.4.  ```OpalHotReloader.alerts_off!``` should turn them off
